### ISSUE TITLE
"WEBP_MUX_ABI_VERSION" not visible

### ISSUE THREAD

**Issue by kozakura913** [NoXF/libwebp-sys#14]
I took an ugly workaround to use WebPAnimEncoder

https://github.com/kozakura913/webp-rs/blob/34a6203e6aaa4303297f1d7e1574b2545e667197/src/encoder.rs#L141

**Comment by NoXF** [comment]
you can use `libwebp_sys::WebPGetMuxABIVersion()` in 0.7.1 now
