### ISSUE TITLE
Possible UB in examples/tests

### ISSUE THREAD

**Issue by nico-abram** [NoXF/libwebp-sys#2]
I believe making a Vec from the data allocated by llibwebp is unsound since that will try to free it with the rust allocator. I think they should be making slices, and then freeing the buffers using `libwebp_sys::WebPFree` (Or maybe another of the free functions).

I'm specifically referring to the decoding examples.

**Comment by NoXF** [comment]
sure. fn decode_webp is just an example of how to use libwebp API. It does not need return Vec in your real program and actually Vec is not allocated by libwebp
