### ISSUE TITLE
Decoding animations

### ISSUE THREAD

**Issue by woelper** [NoXF/libwebp-sys#26]
Hi, and thanks for this great library!

I am trying to decode animations by following this API documentation:
https://developers.google.com/speed/webp/docs/container-api#webpanimdecoder_api

It seems that this requires creation of a `WebPAnimDecoder` (https://docs.rs/libwebp-sys/0.9.4/libwebp_sys/struct.WebPAnimDecoder.html). However this struct has private fields, so I can't construct it. Is there a better or different way to decode animations with this library currently?

**Comment by NoXF** [comment]
so sorry for the late reply, **WebPAnimDecoder** itself is not private, the doc "private field" means property in Decoder is private, but you are not required to access them generally. 

i write a anim decode demo, it independents of any publication. 

```rust
fn test_decode_anim() {
        let mut buf = Vec::new();
        let len = File::open("./tests/test_anim.webp")
            .unwrap()
            .read_to_end(&mut buf)
            .unwrap();

        unsafe {
            let mut width = 0;
            let mut height = 0;
            WebPGetInfo(buf.as_ptr(), len, &mut width, &mut height);
            assert!(width == 400);
            assert!(height == 400);

            let data = WebPData {
                bytes: buf.as_ptr(),
                size: len,
            };

            let mut options = std::mem::zeroed();
            // WebPAnimDecoderOptionsInitInternal(&mut options, WebPGetDemuxABIVersion());
            // let decoder = WebPAnimDecoderNewInternal(&data, &options, WebPGetDemuxABIVersion());
            WebPAnimDecoderOptionsInit(&mut options);
            let decoder = WebPAnimDecoderNew(&data, &options);

            let mut anim_info = WebPAnimInfo::default();
            WebPAnimDecoderGetInfo(decoder, &mut anim_info);

            while WebPAnimDecoderHasMoreFrames(decoder) > 0 {
                let mut frame_buf = std::ptr::null_mut();
                let mut timestamp = 0;
                WebPAnimDecoderGetNext(decoder, &mut frame_buf as *mut *mut u8, &mut timestamp);
            }

            WebPAnimDecoderDelete(decoder);
        }
    }
```

it should be noted that **WebPAnimDecoderOptionsInit** and  **WebPAnimDecoderNew** are not exist in 0.9.4 version, but **WebPAnimDecoderOptionsInitInternal** and **WebPAnimDecoderNewInternal** also works, you can find in commented code.

**WebPAnimDecoderNew** will be added in next version.

**Comment by NoXF** [comment]
add you can detect webp if it has anim before decoding to decide whether to use AnimDecoder. the anim webp should have ANIM and ANMF Chunks.

https://datatracker.ietf.org/doc/html/draft-zern-webp#section-2.7.1.1

**Comment by woelper** [comment]
Thank you so much!
I have looked at web_animation in the meantime, but I would prefer this library as it was much faster in my benchmarks. This is great!
